package update

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"fontget/internal/version"
)

func TestReleaseArchiveName(t *testing.T) {
	tests := []struct {
		version string
		goos    string
		goarch  string
		want    string
	}{
		{"1.2.3", "linux", "amd64", "fontget_1.2.3_linux_amd64.tar.gz"},
		{"1.2.3", "darwin", "arm64", "fontget_1.2.3_darwin_arm64.tar.gz"},
		{"1.2.3", "windows", "arm64", "fontget_1.2.3_windows_arm64.zip"},
	}
	for _, tc := range tests {
		if got := ReleaseArchiveName(tc.version, tc.goos, tc.goarch); got != tc.want {
			t.Errorf("ReleaseArchiveName(%q, %q, %q) = %q, want %q", tc.version, tc.goos, tc.goarch, got, tc.want)
		}
	}
}

func TestParseLatestRedirect(t *testing.T) {
	base := mustURL(t, defaultReleaseBaseURL)
	tests := []struct {
		name     string
		location string
		want     string
		wantErr  bool
	}{
		{
			name:     "absolute",
			location: "https://github.com/Graphixa/FontGet/releases/tag/v1.2.3",
			want:     "1.2.3",
		},
		{
			name:     "relative",
			location: "/Graphixa/FontGet/releases/tag/v2.0.0",
			want:     "2.0.0",
		},
		{
			name:     "wrong host",
			location: "https://evil.example/Graphixa/FontGet/releases/tag/v1.2.3",
			wantErr:  true,
		},
		{
			name:     "wrong repository",
			location: "https://github.com/Someone/Else/releases/tag/v1.2.3",
			wantErr:  true,
		},
		{
			name:     "extra path",
			location: "https://github.com/Graphixa/FontGet/releases/tag/v1.2.3/extra",
			wantErr:  true,
		},
		{
			name:     "malformed semver",
			location: "https://github.com/Graphixa/FontGet/releases/tag/vlatest",
			wantErr:  true,
		},
		{
			name:     "query",
			location: "https://github.com/Graphixa/FontGet/releases/tag/v1.2.3?download=1",
			wantErr:  true,
		},
		{
			name:     "fragment",
			location: "https://github.com/Graphixa/FontGet/releases/tag/v1.2.3#release",
			wantErr:  true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got, err := parseLatestRedirect(base, tc.location)
			if tc.wantErr {
				if err == nil {
					t.Fatalf("expected error, got %s", got)
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if got.String() != tc.want {
				t.Fatalf("got %q, want %q", got, tc.want)
			}
		})
	}
}

func TestValidateDownloadURL(t *testing.T) {
	base := mustURL(t, defaultReleaseBaseURL)
	tests := []struct {
		raw    string
		wantOK bool
	}{
		{"https://github.com/Graphixa/FontGet/releases/download/v1.2.3/checksums.txt", true},
		{"https://objects.githubusercontent.com/github-production-release-asset/file", true},
		{"https://release-assets.githubusercontent.com/file", true},
		{"https://evil.example/fontget.tar.gz", false},
		{"http://github.com/Graphixa/FontGet/releases/download/v1.2.3/checksums.txt", false},
		{"file:///etc/passwd", false},
	}
	for _, tc := range tests {
		err := validateDownloadURL(mustURL(t, tc.raw), base)
		if tc.wantOK && err != nil {
			t.Errorf("%s: unexpected error: %v", tc.raw, err)
		}
		if !tc.wantOK && err == nil {
			t.Errorf("%s: expected rejection", tc.raw)
		}
	}
}

func TestParseChecksums(t *testing.T) {
	const hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	content := hash + "  fontget_1.2.3_linux_amd64.tar.gz\n" +
		strings.ToUpper(hash) + " *fontget_1.2.3_windows_amd64.zip\n" +
		"# generated by GoReleaser\n"

	sums, err := parseChecksums([]byte(content))
	if err != nil {
		t.Fatal(err)
	}
	if sums["fontget_1.2.3_linux_amd64.tar.gz"] != hash {
		t.Fatalf("linux hash = %q", sums["fontget_1.2.3_linux_amd64.tar.gz"])
	}
	if sums["fontget_1.2.3_windows_amd64.zip"] != hash {
		t.Fatalf("windows hash = %q", sums["fontget_1.2.3_windows_amd64.zip"])
	}
}

func TestParseChecksumsRejectsInvalidInput(t *testing.T) {
	const hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	tests := []struct {
		name    string
		content string
	}{
		{"empty", ""},
		{"bad hash", "not-a-hash  fontget.tar.gz\n"},
		{"missing filename", hash + "\n"},
		{"extra field", hash + "  fontget.tar.gz extra\n"},
		{"path filename", hash + "  subdir/fontget.tar.gz\n"},
		{"duplicate", hash + "  fontget.tar.gz\n" + hash + "  fontget.tar.gz\n"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := parseChecksums([]byte(tc.content)); err == nil {
				t.Fatal("expected error")
			}
		})
	}
}

func TestChecksumForExactPlatformArchive(t *testing.T) {
	const hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	content := []byte(hash + "  fontget_1.2.3_linux_amd64.tar.gz\n" +
		hash + "  fontget_1.2.3_linux_arm64.tar.gz\n" +
		hash + "  fontget_1.2.3_amd64.deb\n")

	got, err := checksumForFile(content, "fontget_1.2.3_linux_amd64.tar.gz")
	if err != nil {
		t.Fatal(err)
	}
	if got != hash {
		t.Fatalf("got %q, want %q", got, hash)
	}
	if _, err := checksumForFile(content, "fontget_1.2.3_windows_amd64.zip"); err == nil {
		t.Fatal("expected missing platform archive error")
	}
}

func TestVerifySHA256(t *testing.T) {
	data := []byte("hello")
	sum := sha256.Sum256(data)
	if err := verifySHA256(data, hex.EncodeToString(sum[:])); err != nil {
		t.Fatal(err)
	}
	if err := verifySHA256(data, strings.Repeat("b", 64)); err == nil {
		t.Fatal("expected mismatch")
	}
}

func TestLatestVersionDiscovery(t *testing.T) {
	var srv *httptest.Server
	srv = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/Graphixa/FontGet/releases/latest" {
			http.NotFound(w, r)
			return
		}
		http.Redirect(w, r, srv.URL+"/Graphixa/FontGet/releases/tag/v1.2.3", http.StatusFound)
	}))
	defer srv.Close()
	setReleaseBase(t, srv.URL+"/Graphixa/FontGet/releases")

	client, err := newReleaseClient()
	if err != nil {
		t.Fatal(err)
	}
	got, err := client.latestVersion(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if got.String() != "1.2.3" {
		t.Fatalf("got %q, want 1.2.3", got)
	}
}

func TestLatestVersionNotFound(t *testing.T) {
	srv := httptest.NewServer(http.NotFoundHandler())
	defer srv.Close()
	setReleaseBase(t, srv.URL+"/Graphixa/FontGet/releases")

	client, err := newReleaseClient()
	if err != nil {
		t.Fatal(err)
	}
	_, err = client.latestVersion(context.Background())
	if !errors.Is(err, errReleaseNotFound) {
		t.Fatalf("got %v, want errReleaseNotFound", err)
	}
}

func TestCheckForUpdatesUsesOnlyLatestRedirect(t *testing.T) {
	requests := make([]string, 0, 1)
	var srv *httptest.Server
	srv = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests = append(requests, r.URL.Path)
		http.Redirect(w, r, srv.URL+"/Graphixa/FontGet/releases/tag/v1.2.3", http.StatusFound)
	}))
	defer srv.Close()
	setReleaseBase(t, srv.URL+"/Graphixa/FontGet/releases")
	setVersion(t, "1.0.0")

	result, err := CheckForUpdates()
	if err != nil {
		t.Fatal(err)
	}
	if !result.Available || !result.NeedsUpdate || result.Latest != "1.2.3" {
		t.Fatalf("unexpected result: %+v", result)
	}
	if len(requests) != 1 || requests[0] != "/Graphixa/FontGet/releases/latest" {
		t.Fatalf("unexpected requests: %v", requests)
	}
}

func TestCheckForUpdatesWithoutRelease(t *testing.T) {
	srv := httptest.NewServer(http.NotFoundHandler())
	defer srv.Close()
	setReleaseBase(t, srv.URL+"/Graphixa/FontGet/releases")
	setVersion(t, "1.0.0")

	result, err := CheckForUpdates()
	if err != nil {
		t.Fatal(err)
	}
	if result.Available || result.NeedsUpdate {
		t.Fatalf("expected no release, got %+v", result)
	}
}

func TestUpdateToLatestUsesImmutableTaggedAssets(t *testing.T) {
	setTestPlatform(t, "linux", "amd64")
	setNoMigration(t)
	setVersion(t, "1.0.0")

	payload := []byte("updated-fontget")
	archive := mustTarGz(t, "fontget", payload)
	archiveName := "fontget_1.2.3_linux_amd64.tar.gz"
	checksums := checksumLine(archive, archiveName)

	var requests []string
	var authorizationSeen bool
	var srv *httptest.Server
	srv = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests = append(requests, r.URL.Path)
		authorizationSeen = authorizationSeen || r.Header.Get("Authorization") != ""
		switch r.URL.Path {
		case "/Graphixa/FontGet/releases/latest":
			http.Redirect(w, r, srv.URL+"/Graphixa/FontGet/releases/tag/v1.2.3", http.StatusFound)
		case "/Graphixa/FontGet/releases/download/v1.2.3/checksums.txt":
			_, _ = io.WriteString(w, checksums)
		case "/Graphixa/FontGet/releases/download/v1.2.3/" + archiveName:
			_, _ = w.Write(archive)
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()
	setReleaseBase(t, srv.URL+"/Graphixa/FontGet/releases")

	dest := prepareExecutable(t, []byte("old"))
	if err := UpdateToLatest(); err != nil {
		t.Fatal(err)
	}
	assertFileContents(t, dest, payload)
	if authorizationSeen {
		t.Fatal("self-update requests must not include Authorization")
	}

	want := []string{
		"/Graphixa/FontGet/releases/latest",
		"/Graphixa/FontGet/releases/download/v1.2.3/checksums.txt",
		"/Graphixa/FontGet/releases/download/v1.2.3/" + archiveName,
	}
	if strings.Join(requests, "\n") != strings.Join(want, "\n") {
		t.Fatalf("requests:\n%v\nwant:\n%v", requests, want)
	}
}

func TestUpdateToVersionSkipsLatestDiscovery(t *testing.T) {
	setTestPlatform(t, "windows", "amd64")
	setNoMigration(t)

	payload := []byte("updated-windows-fontget")
	archive := mustZip(t, "fontget.exe", payload)
	archiveName := "fontget_2.0.0_windows_amd64.zip"
	checksums := checksumLine(archive, archiveName)

	var requests []string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests = append(requests, r.URL.Path)
		switch r.URL.Path {
		case "/Graphixa/FontGet/releases/download/v2.0.0/checksums.txt":
			_, _ = io.WriteString(w, checksums)
		case "/Graphixa/FontGet/releases/download/v2.0.0/" + archiveName:
			_, _ = w.Write(archive)
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()
	setReleaseBase(t, srv.URL+"/Graphixa/FontGet/releases")

	dest := prepareExecutable(t, []byte("old"))
	if err := UpdateToVersion("2.0.0"); err != nil {
		t.Fatal(err)
	}
	assertFileContents(t, dest, payload)
	for _, requestPath := range requests {
		if strings.HasSuffix(requestPath, "/latest") {
			t.Fatalf("specific update unexpectedly requested latest: %v", requests)
		}
	}
}

func TestUpdateRejectsChecksumMismatch(t *testing.T) {
	setTestPlatform(t, "linux", "amd64")
	archive := mustTarGz(t, "fontget", []byte("payload"))
	archiveName := "fontget_1.2.3_linux_amd64.tar.gz"
	badChecksums := strings.Repeat("a", 64) + "  " + archiveName + "\n"

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/Graphixa/FontGet/releases/download/v1.2.3/checksums.txt":
			_, _ = io.WriteString(w, badChecksums)
		case "/Graphixa/FontGet/releases/download/v1.2.3/" + archiveName:
			_, _ = w.Write(archive)
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()
	setReleaseBase(t, srv.URL+"/Graphixa/FontGet/releases")

	err := UpdateToVersion("1.2.3")
	if err == nil || !strings.Contains(err.Error(), "verification failed") {
		t.Fatalf("expected verification error, got %v", err)
	}
}

func TestUpdateRejectsMissingPlatformChecksum(t *testing.T) {
	setTestPlatform(t, "linux", "amd64")
	checksums := strings.Repeat("a", 64) + "  fontget_1.2.3_linux_arm64.tar.gz\n"

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasSuffix(r.URL.Path, "/checksums.txt") {
			_, _ = io.WriteString(w, checksums)
			return
		}
		http.NotFound(w, r)
	}))
	defer srv.Close()
	setReleaseBase(t, srv.URL+"/Graphixa/FontGet/releases")

	err := UpdateToVersion("1.2.3")
	if err == nil || !strings.Contains(err.Error(), "does not contain") {
		t.Fatalf("expected missing checksum error, got %v", err)
	}
}

func TestUpdateRejectsUntrustedAssetRedirect(t *testing.T) {
	setTestPlatform(t, "linux", "amd64")
	archive := mustTarGz(t, "fontget", []byte("payload"))
	archiveName := "fontget_1.2.3_linux_amd64.tar.gz"
	checksums := checksumLine(archive, archiveName)

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case strings.HasSuffix(r.URL.Path, "/checksums.txt"):
			_, _ = io.WriteString(w, checksums)
		case strings.HasSuffix(r.URL.Path, "/"+archiveName):
			http.Redirect(w, r, "https://evil.example/fontget.tar.gz", http.StatusFound)
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()
	setReleaseBase(t, srv.URL+"/Graphixa/FontGet/releases")

	err := UpdateToVersion("1.2.3")
	if err == nil || !strings.Contains(err.Error(), "untrusted host") {
		t.Fatalf("expected untrusted host error, got %v", err)
	}
}

func TestExtractBinaryZipAndTarGz(t *testing.T) {
	payload := []byte("fake-fontget-binary")

	setTestPlatform(t, "linux", "amd64")
	got, err := extractBinary(mustTarGz(t, "fontget", payload), "fontget_1.2.3_linux_amd64.tar.gz")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, payload) {
		t.Fatalf("tar.gz extracted %q", got)
	}

	currentGOOS = "windows"
	got, err = extractBinary(mustZip(t, "fontget.exe", payload), "fontget_1.2.3_windows_amd64.zip")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, payload) {
		t.Fatalf("zip extracted %q", got)
	}
}

func TestExtractBinaryRejectsMissingAndUnsafeEntries(t *testing.T) {
	setTestPlatform(t, "linux", "amd64")
	if _, err := extractBinary(mustTarGz(t, "readme.txt", []byte("nope")), "fontget_1.2.3_linux_amd64.tar.gz"); err == nil {
		t.Fatal("expected missing binary error")
	}
	if _, err := extractBinary(mustZip(t, "../fontget", []byte("escaped")), "fontget_1.2.3_linux_amd64.zip"); err == nil {
		t.Fatal("expected unsafe path to be rejected")
	}
}

func TestReplaceExecutableAndCleanup(t *testing.T) {
	dir := t.TempDir()
	dest := filepath.Join(dir, "fontget")
	if err := os.WriteFile(dest, []byte("old"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := replaceExecutable(dest, []byte("new")); err != nil {
		t.Fatal(err)
	}
	assertFileContents(t, dest, []byte("new"))
	if _, err := os.Stat(dest + ".old"); err != nil {
		t.Fatalf(".old should remain until cleanup: %v", err)
	}
	cleanupOldBinary(dest)
	if _, err := os.Stat(dest + ".old"); !os.IsNotExist(err) {
		t.Fatalf("cleanup should remove .old, err=%v", err)
	}
}

func TestParseVersion(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"v1.2.3", "1.2.3"},
		{"1.2.3", "1.2.3"},
		{"dev", "0.0.0"},
		{"dev-20260101120000-abc", "0.0.0"},
	}
	for _, tc := range tests {
		got, err := parseVersion(tc.input)
		if err != nil {
			t.Fatalf("%q: %v", tc.input, err)
		}
		if got.String() != tc.want {
			t.Fatalf("%q: got %q, want %q", tc.input, got, tc.want)
		}
	}
}

func mustURL(t *testing.T, raw string) *url.URL {
	t.Helper()
	u, err := url.Parse(raw)
	if err != nil {
		t.Fatal(err)
	}
	return u
}

func setReleaseBase(t *testing.T, base string) {
	t.Helper()
	previous := releaseBaseURL
	releaseBaseURL = base
	t.Cleanup(func() { releaseBaseURL = previous })
}

func setVersion(t *testing.T, value string) {
	t.Helper()
	previous := version.Version
	version.Version = value
	t.Cleanup(func() { version.Version = previous })
}

func setTestPlatform(t *testing.T, goos, goarch string) {
	t.Helper()
	previousOS, previousArch := currentGOOS, currentGOARCH
	currentGOOS, currentGOARCH = goos, goarch
	t.Cleanup(func() {
		currentGOOS, currentGOARCH = previousOS, previousArch
	})
}

func setNoMigration(t *testing.T) {
	t.Helper()
	previous := migrateAfterUpdate
	migrateAfterUpdate = func() error { return nil }
	t.Cleanup(func() { migrateAfterUpdate = previous })
}

func prepareExecutable(t *testing.T, content []byte) string {
	t.Helper()
	previous := executablePath
	dest := filepath.Join(t.TempDir(), currentExecutableName())
	if err := os.WriteFile(dest, content, 0o755); err != nil {
		t.Fatal(err)
	}
	executablePath = func() (string, error) { return dest, nil }
	t.Cleanup(func() { executablePath = previous })
	return dest
}

func assertFileContents(t *testing.T, path string, want []byte) {
	t.Helper()
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("%s contains %q, want %q", path, got, want)
	}
}

func checksumLine(data []byte, name string) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]) + "  " + name + "\n"
}

func mustZip(t *testing.T, name string, payload []byte) []byte {
	t.Helper()
	var buf bytes.Buffer
	w := zip.NewWriter(&buf)
	f, err := w.Create(name)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := f.Write(payload); err != nil {
		t.Fatal(err)
	}
	if err := w.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func mustTarGz(t *testing.T, name string, payload []byte) []byte {
	t.Helper()
	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gz)
	hdr := &tar.Header{
		Name: name,
		Mode: 0o755,
		Size: int64(len(payload)),
	}
	if err := tw.WriteHeader(hdr); err != nil {
		t.Fatal(err)
	}
	if _, err := tw.Write(payload); err != nil {
		t.Fatal(err)
	}
	if err := tw.Close(); err != nil {
		t.Fatal(err)
	}
	if err := gz.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}
