# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

project_name: fontget
dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: fontget
    main: .
    binary: fontget
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X fontget/internal/version.Version={{.Version}}
      - -X fontget/internal/version.GitCommit={{.Commit}}
      - -X fontget/internal/version.BuildDate={{.Date}}

archives:
  - id: default
    ids:
      - fontget
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT"

release:
  # Upload raw binaries in addition to archives (required for self-update system)
  # The self-update library expects binaries named: fontget-{os}-{arch}{.ext}
  # GoReleaser builds binaries to dist/{build_id}_{os}_{arch}_{version}/binary_name
  # We use glob patterns with name_template to rename them correctly
  extra_files:
    - glob: dist/fontget_windows_amd64*/fontget.exe
      name_template: fontget-windows-amd64.exe
    - glob: dist/fontget_windows_arm64*/fontget.exe
      name_template: fontget-windows-arm64.exe
    - glob: dist/fontget_darwin_amd64*/fontget
      name_template: fontget-darwin-amd64
    - glob: dist/fontget_darwin_arm64*/fontget
      name_template: fontget-darwin-arm64
    - glob: dist/fontget_linux_amd64*/fontget
      name_template: fontget-linux-amd64
    - glob: dist/fontget_linux_arm64*/fontget
      name_template: fontget-linux-arm64

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Linux packages via NFPM (deb/rpm)
nfpms:
  - id: linux-packages
    ids:
      - fontget
    package_name: fontget
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: "Graphixa <https://github.com/Graphixa>"
    description: "FontGet CLI tool for managing fonts"
    license: "MIT"
    vendor: "Graphixa"
    homepage: "https://github.com/Graphixa/FontGet"
    section: utils
    bindir: /usr/bin
    # GoReleaser automatically filters to Linux builds and includes binaries from 'builds'
    # The binary will be placed in /usr/bin/fontget

# Homebrew Cask (macOS)
# Using homebrew_casks instead of deprecated brews (since GoReleaser v2.10)
homebrew_casks:
  - name: fontget
    repository:
      owner: Graphixa
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/Graphixa/FontGet"
    description: "A tiny, cross-platform CLI tool to install and manage fonts from the command line. Search for fonts, list installed fonts, install or remove fonts all from the CLI."
    license: "MIT"
    # Use the default archive (darwin builds only)
    # GoReleaser will automatically filter to darwin archives
    ids:
      - default
    binaries:
      - fontget
    # Remove quarantine attribute to allow execution on macOS
    # This is required for unsigned binaries from GitHub releases
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fontget"]
          end

# Scoop bucket (Windows)
# Using repository instead of deprecated bucket field
scoops:
  - name: fontget
    repository:
      owner: Graphixa
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    homepage: "https://github.com/Graphixa/FontGet"
    description: "A tiny, cross-platform CLI tool to install and manage fonts from the command line. Search for fonts, list installed fonts, install or remove fonts all from the CLI."
    license: "MIT"

# Chocolatey (Windows)
# GoReleaser can build Chocolatey packages on Ubuntu - it generates .nupkg files internally
# and pushes them via HTTP using the API key. No choco CLI needed.
chocolateys:
  - name: fontget
    ids:
      - default
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    title: "FontGet"
    owners: "Graphixa"
    authors: "Graphixa"
    project_url: "https://github.com/Graphixa/FontGet"
    project_source_url: "https://github.com/Graphixa/FontGet"
    package_source_url: "https://github.com/Graphixa/FontGet"
    description: "A tiny, cross-platform CLI tool to install and manage fonts from the command line. Search for fonts, list installed fonts, install or remove fonts all from the CLI."
    summary: "Install and manage fonts from the command line"
    tags: "fonts,font-manager,cli,cross-platform"
    license_url: "https://github.com/Graphixa/FontGet/blob/main/LICENSE"
    release_notes: "https://github.com/Graphixa/FontGet/releases/tag/v{{ .Version }}"
    bug_tracker_url: "https://github.com/Graphixa/FontGet/issues"
    docs_url: "https://github.com/Graphixa/FontGet/blob/main/README.md"

# Winget (Windows) - Automated PRs to microsoft/winget-pkgs
winget:
  - name: fontget
    # Publisher name (required)
    publisher: Graphixa
    
    # Required fields
    short_description: "A tiny, cross-platform CLI tool to install and manage fonts from the command line"
    license: "mit"  # License name (lowercase, e.g., "mit", "apache-2.0")
    
    # IDs of the archives to use (empty means all IDs)
    # We use the default archive which contains Windows builds
    ids:
      - default
    
    # GOAMD64 to specify which amd64 version to use if there are multiple versions
    # Default: 'v1' (we only build one amd64 version, so default is fine)
    goamd64: v1
    
    # Package identifier
    # Using FontGet.FontGet to match open-source project naming convention
    # (similar to Inkscape.Inkscape, Git.Git, etc.)
    # This overrides the default Publisher.ProjectName (Graphixa.FontGet)
    package_identifier: FontGet.FontGet
    
    # Commit message template
    # Templates: allowed
    commit_msg_template: "{{ .PackageIdentifier }}: {{ .Tag }}"
    
    # URL template for downloading the installer/archive
    # Default for GitHub: https://github.com/<owner>/<repo>/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    # We're explicit here to ensure it matches our archive naming: fontget_<version>_windows_<arch>.zip
    url_template: "https://github.com/Graphixa/FontGet/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    
    # Path for manifests inside the repository
    # Default: manifests/<lowercased first char of publisher>/<publisher>/<name>/<version>
    # Since we use package_identifier: FontGet.FontGet, the path should match:
    # Templates: allowed
    path: manifests/f/FontGet/FontGet/{{.Version}}
    
    # Optional but recommended fields
    homepage: "https://github.com/Graphixa/FontGet"
    description: "A tiny, cross-platform CLI tool to install and manage fonts from the command line. Search for fonts, list installed fonts, install or remove fonts all from the CLI."
    license_url: "https://github.com/Graphixa/FontGet/blob/main/LICENSE"
    publisher_url: "https://github.com/Graphixa"
    publisher_support_url: "https://github.com/Graphixa/FontGet/issues"
    
    # Release notes - use changelog content generated by GoReleaser
    # Templates: allowed
    release_notes: "{{.Changelog}}"
    
    # Release notes URL (separate from release_notes content)
    # Templates: allowed
    release_notes_url: "https://github.com/Graphixa/FontGet/releases/tag/v{{.Version}}"
    
    # Copyright information (optional but recommended)
    copyright: "Copyright (c) Graphixa"
    copyright_url: "https://github.com/Graphixa/FontGet/blob/main/LICENSE"
    
    # Installation notes (optional but helpful for users)
    installation_notes: "FontGet will be installed to your PATH. Run 'fontget --help' to get started."
    
    # Tags (GoReleaser converts to lowercase and replaces spaces with hyphens)
    # Used for discoverability in winget search
    tags:
      - fonts
      - font-management
      - nerd-fonts
      - google-fonts
      - font-manager
      - cli
      - command-line
      - cross-platform
      - utility
      - typography
      - terminal
    
    # Repository configuration for your fork
    repository:
      # Your fork of microsoft/winget-pkgs
      owner: Graphixa  # Your GitHub username or organization
      name: winget-pkgs
      # Feature branch for each release (different from base branch)
      branch: "fontget-{{ .Version }}"
      # Use personal access token from GitHub secret
      token: "{{ .Env.WINGET_PR_TOKEN }}"
      
      # Enable pull request creation
      pull_request:
        enabled: true
        # Open PR as ready for review (fully automated)
        draft: false
        # Base repository (where the PR will be opened)
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master  # microsoft/winget-pkgs uses 'master' as default branch