project_name: fontget
dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: fontget
    main: .
    binary: fontget
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X fontget/internal/version.Version={{.Version}}
      - -X fontget/internal/version.GitCommit={{.Commit}}
      - -X fontget/internal/version.BuildDate={{.Date}}

archives:
  - id: default
    builds:
      - fontget
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

release:
  # Upload raw binaries in addition to archives (required for self-update system)
  # The self-update library expects binaries named: fontget-{os}-{arch}{.ext}
  # GoReleaser builds binaries to dist/{build_id}_{os}_{arch}_{version}/binary_name
  # We use glob patterns with name_template to rename them correctly
  extra_files:
    - glob: dist/fontget_windows_amd64*/fontget.exe
      name_template: fontget-windows-amd64.exe
    - glob: dist/fontget_windows_arm64*/fontget.exe
      name_template: fontget-windows-arm64.exe
    - glob: dist/fontget_darwin_amd64*/fontget
      name_template: fontget-darwin-amd64
    - glob: dist/fontget_darwin_arm64*/fontget
      name_template: fontget-darwin-arm64
    - glob: dist/fontget_linux_amd64*/fontget
      name_template: fontget-linux-amd64
    - glob: dist/fontget_linux_arm64*/fontget
      name_template: fontget-linux-arm64

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Linux packages via NFPM (deb/rpm)
nfpms:
  - id: linux-packages
    builds:
      - fontget
    package_name: fontget
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: "Graphixa <https://github.com/Graphixa>"
    description: "FontGet CLI tool for managing fonts"
    license: "MIT"
    vendor: "Graphixa"
    homepage: "https://github.com/Graphixa/FontGet"
    section: utils
    bindir: /usr/bin
    # GoReleaser automatically filters to Linux builds and includes binaries from 'builds'
    # The binary will be placed in /usr/bin/fontget

